version: '3.8'

services:
  # Database Service
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=feedback_db
    ports:
      - "3306:3306"
    networks:
      - feedback-net
    volumes:
      - db_data:/var/lib/mysql

  # Backend Service
  backend:
    build: ./feedback-backend  # Ensure this matches your folder name
    container_name: feedback-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/feedback_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - mysqldb
    networks:
      - feedback-net

  # Frontend Service
  frontend:
    build: ./feedback-frontend
    container_name: feedback-frontend
    ports:
      - "4200:80" 
    depends_on:
      - backend
    networks:
      - feedback-net

networks:
  feedback-net:
    driver: bridge

volumes:
  db_data: